
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Screenshot Testing
android.experimental.enableScreenshotTest=true

# AGP 9.0 Compatibility for KMP
android.builtInKotlin=false
android.newDsl=false
android.sourceset.disallowProvider=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL

# KSP
ksp.version.check=false
ksp.useClasspathSnapshot=false
