package com.spresso.engage

object Constants {
    const val REPEAT_INTERVAL = 24L
    const val MAX_PUBLISHING_ATTEMPTS = 3
    const val PUBLISH_TYPE_KEY = "PUBLISH_TYPE"
    const val PUBLISH_TYPE_RECOMMENDATIONS = "RECOMMENDATIONS"
    const val PUBLISH_TYPE_FEATURED = "FEATURED"
    const val PUBLISH_TYPE_SHOPPING_CART = "SHOPPING_CART"
    const val PUBLISH_TYPE_SHOPPING_LIST = "SHOPPING_LIST"
    const val PUBLISH_TYPE_SHOPPING_REORDER = "SHOPPING_REORDER"
    const val PUBLISH_TYPE_SHOPPING_ORDER_TRACKING = "SHOPPING_ORDER_TRACKING"
}
