extend type Order {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Order", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Order` table.
  """
  _count: Int! @fdc_generated(from: "Order.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `authorizationId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  authorizationId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.authorizationId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `deviceSource` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  deviceSource_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.deviceSource", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `paymentMethod` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  paymentMethod_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.paymentMethod", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.productId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `quantity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  quantity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.quantity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Order` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Order.userUid", purpose: QUERY_COUNT)
  """
  ✨ Sum the `quantity` field in the `Order` table.
  """
  quantity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Order.quantity", purpose: QUERY_SUM)
  """
  ✨ Average the `quantity` field in the `Order` table.
  """
  quantity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Order.quantity", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Order` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Order.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `quantity` field in the `Order` table.
  """
  quantity_min: Int @fdc_generated(from: "Order.quantity", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Order` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Order.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `quantity` field in the `Order` table.
  """
  quantity_max: Int @fdc_generated(from: "Order.quantity", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Order.id", purpose: ENTITY_ID)
}
extend type Product {
  """
  ✨ List `Order` objects in a one-to-many relationship (where `Order`.`product` is this object).
  """
  orders_on_product(
    """
    Filter condition to narrow down the query results.
    """
    where: Order_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Order_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Order_Having
  ): [Order!]! @fdc_generated(from: "Order.product", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserLike` objects in a one-to-many relationship (where `UserLike`.`product` is this object).
  """
  userLikes_on_product(
    """
    Filter condition to narrow down the query results.
    """
    where: UserLike_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserLike_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserLike_Having
  ): [UserLike!]! @fdc_generated(from: "UserLike.product", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Product", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Product` table.
  """
  _count: Int! @fdc_generated(from: "Product.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `likesCount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  likesCount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.likesCount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `price` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  price_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.price", purpose: QUERY_COUNT)
  """
  ✨ Sum the `likesCount` field in the `Product` table.
  """
  likesCount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Product.likesCount", purpose: QUERY_SUM)
  """
  ✨ Sum the `price` field in the `Product` table.
  """
  price_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.price", purpose: QUERY_SUM)
  """
  ✨ Average the `likesCount` field in the `Product` table.
  """
  likesCount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.likesCount", purpose: QUERY_AVG)
  """
  ✨ Average the `price` field in the `Product` table.
  """
  price_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.price", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `likesCount` field in the `Product` table.
  """
  likesCount_min: Int @fdc_generated(from: "Product.likesCount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `price` field in the `Product` table.
  """
  price_min: Float @fdc_generated(from: "Product.price", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `likesCount` field in the `Product` table.
  """
  likesCount_max: Int @fdc_generated(from: "Product.likesCount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `price` field in the `Product` table.
  """
  price_max: Float @fdc_generated(from: "Product.price", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Product.id", purpose: ENTITY_ID)
}
extend type UserLike {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserLike", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserLike` table.
  """
  _count: Int! @fdc_generated(from: "UserLike.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserLike` table where the `productId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserLike.productId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserLike` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserLike.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserLike` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserLike.userUid", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `UserLike` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "UserLike.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `UserLike` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "UserLike.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserLike.userUid,productId", purpose: ENTITY_ID)
}
