default_platform(:android)

platform :android do
  desc "Automated Canary Deployment to Google Play Internal Testing"
  lane :deploy_internal do
    gradle(
      task: ":androidApp:bundleRelease",
      project_dir: File.expand_path("..", __dir__)
    )

    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      aab: 'androidApp/build/outputs/bundle/release/androidApp-release.aab'
    )
  end
end
