package network

object FirebaseRoutes {
    const val GENERATE_VIRTUAL_TRY_ON = "generateVirtualTryOn"
    const val GENERATE_SPIN_360 = "generateSpin360"
    const val GENERATE_LIVE_API_TOKEN = "generateLiveApiToken"
    const val LENS_SEARCH = "lensSearch"
    const val CREATOR_AGENT_TEMPLATES = "creatorAgentTemplates"
    const val GENERATE_CREATOR_CAMPAIGN = "generateCreatorCampaign"
    const val VITPOSE_ORCHESTRATE_FIT = "vitposeOrchestrateFit"
    const val GET_QUICK_PROMPTS = "getQuickPrompts"
    const val LOG_SEARCH_HISTORY = "logSearchHistory"
    const val CHAT_STREAM = "chatStream"
    const val DISCOVER_PERSONALIZED_PRODUCTS = "discoverPersonalizedProducts"
    const val ANALYZE_USER_BEHAVIOR = "analyzeUserBehavior"
    const val VERIFY_EMAIL_CREDENTIAL = "verifyEmailCredential"
    const val INGEST_INTERACTION = "ingestInteraction"
    const val INITIATE_ORDER_RETURN = "initiateOrderReturn"
    const val SET_ORDER_REMINDER = "setOrderReminder"
    const val GENERATE_RECIPE_BARGAIN_CHEF = "generateRecipeBargainChef"
    const val GET_USER_PROFILE = "getUserProfile"
    const val UPDATE_USER_PROFILE = "updateUserProfile"
    const val DEACTIVATE_ACCOUNT = "deactivateAccount"
    const val GET_TRAVEL_TRIPS = "getTravelTrips"
    const val INITIALIZE_ONBOARDING = "initializeOnboarding"
    const val CONNECT_COINBASE_WALLET = "connectCoinbaseWallet"
    const val GENERATE_RESPONSE_FROM_AUDIO = "generateResponseFromAudio"

    const val GENERATE_GOOGLE_WALLET_PASS_JWT = "generateGoogleWalletPassJwt"
    const val GET_USER_PREFERENCES = "getUserPreferences"
    const val UPDATE_USER_PREFERENCES = "updateUserPreferences"
    const val TOGGLE_USER_LIKE = "toggleUserLike"
    const val FETCH_PRODUCTS_BY_IDS = "fetchProductsByIds"
    const val GENERATE_OUTFIT = "generateOutfit"
}
