package network

object FirebaseRoutes {
    const val GENERATE_VIRTUAL_TRY_ON = "generateVirtualTryOn"
    const val GENERATE_SPIN_360 = "generateSpin360"
    const val GENERATE_LIVE_API_TOKEN = "generateLiveApiToken"
    const val IDENTIFY_VISION_OBJECT = "identifyVisionObject"
    const val CREATOR_AGENT_TEMPLATES = "creatorAgentTemplates"
    const val GENERATE_CREATOR_CAMPAIGN = "generateCreatorCampaign"
    const val VITPOSE_ORCHESTRATE_FIT = "vitposeOrchestrateFit"
    const val GET_QUICK_PROMPTS = "getQuickPrompts"
    const val LOG_SEARCH_HISTORY = "logSearchHistory"
    const val CHAT_STREAM = "chatStream"
    const val GET_INVENTORY_PROXY = "getInventoryProxy"
    const val DISCOVER_PERSONALIZED_PRODUCTS = "discoverPersonalizedProducts"
    const val ANALYZE_USER_BEHAVIOR = "analyzeUserBehavior"
    const val VERIFY_EMAIL_CREDENTIAL = "verifyEmailCredential"
    const val INGEST_INTERACTION = "ingestInteraction"
    const val CONFIRM_PURCHASE = "confirmPurchase"
    const val INITIATE_ORDER_RETURN = "initiateOrderReturn"
    const val SET_ORDER_REMINDER = "setOrderReminder"
    const val GENERATE_RECIPE_BARGAIN_CHEF = "generateRecipeBargainChef"
    const val GET_USER_PROFILE = "getUserProfile"
    const val UPDATE_USER_PROFILE = "updateUserProfile"
    const val DEACTIVATE_ACCOUNT = "deactivateAccount"
    const val GET_TRAVEL_TRIPS = "getTravelTrips"
    const val GET_TRAVEL_EVENTS = "getTravelEvents"
    const val GET_TRAVEL_EXPENSES = "getTravelExpenses"
    const val GET_VOICE_NOTES = "getVoiceNotes"
    const val GET_GROCERY_ITEMS = "getGroceryItems"
    const val GET_VISION_DETECTION = "getVisionDetection"
    const val GET_SAVED_RECIPE = "getSavedRecipe"
    const val FETCH_PRODUCTS_BY_IDS = "fetchProductsByIds"
    const val GET_USER_ORDERS = "getUserOrders"
    const val CONNECT_COINBASE_WALLET = "connectCoinbaseWallet"
    const val INITIALIZE_ONBOARDING = "initializeOnboarding"
    const val GENERATE_RESPONSE_FROM_AUDIO = "generateResponseFromAudio"
    const val GENERATE_PASSKEY_CHALLENGE = "generatePasskeyChallenge"
    const val VERIFY_PASSKEY_REGISTRATION = "verifyPasskeyRegistration"
    const val GENERATE_GOOGLE_WALLET_PASS_JWT = "generateGoogleWalletPassJwt"
}
